---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  engine = 'python',
  fig.path = "README-"
)
```

# NumPy

## Array Creation Function

Function | Description
-------- | -----------
array    | Convert input data (list, tuple, array, or other sequence type) to an ndarray either by inferring a dtype or explicitly specifying a dtype. Copies the input data by default.
asarray  | Convert input to ndarray, but do not copy if the input is already an ndarray
arange   | Like the built-in range but returns an ndarray instead of a list.
ones, ones\_like | Produce an array of all 1’s with the given shape and dtype. ones_like takes another array and produces a ones array of the same shape and dtype.
zeros, zeros\_like | Like ones and ones_like but producing arrays of 0’s instead
empty, empty\_like | Create new arrays by allocating new memory, but do not populate with any values like ones and zeros
eye, identity | Create a square N x N identity matrix (1’s on the diagonal and 0’s elsewhere)

## NumPy Data Types

Type | Type Code | Description
---- | --------- | -----------
int8, uint8 | i1, u1 | Signed and unsigned 8-bit (1 byte) integer types
int16, uint16 | i2, u2 | Signed and unsigned 16-bit integer types
int32, uint32 | i4, u4 | Signed and unsigned 32-bit integer types
int64, uint64 | i8, u8 | Signed and unsigned 32-bit integer types
float16 | f2 | Half-precision floating point
float32 | f4 or f | Standard single-precision floating point. Compatible with C float
float64, float128 | f8 or d | Standard double-precision floating point. Compatible with C double and Python `float` object
float128 | f16 or g | Extended-precision floating point
complex64, complex128, complex256 | c8, c16, c32| Complex numbers represented by two 32, 64, or 128 floats, respectively
bool | ? | Boolean type storing True and False values
object | O | Python object type
string_ | S | Fixed-length string type (1 byte per character). For example, to create a string dtype with length 10, use 'S10'.
unicode_ | U | Fixed-length unicode type (number of bytes platform specific). Same specification semantics as string_ (e.g. 'U10').

+ Calling ndarray's `astype` method can convert or `cast` an array from one dtype to another.

+ Calling `astype` always creates a new array (a copy of the data), even if the new dtype is the same as the old dtype.

## NumPy Basic Indexing and Slicing

+ An important first distinction from lists is that array slices are views on the original array. This means that the data is not copied, and any modifications to the view will be reflected in the source array.

+ If you want a copy of a slice of an ndarray instead of a view, you will need to explicitly copy the array; for example `arr[5:8].copy()`.

+ Indexing with integer and indexing with slice, like in `R`, as a consequence on result's dimension - an `3 x 3` array, `arr[2, :]` gives a view of one dimension array whereas `arr[2:, :]` gives a view of two dimension `1 x 3` array.

+ Selecting data from an array by boolean indexing always creates a copy of the data, even if the returned array is unchanged.

## NumPy Fancy Indexing

+ Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays.

+ Passing multiple index arrays selects a 1D array of elements corresponding to each tuple of indices. To select the rectangular region formed by selecting a subset of the matrix’s rows and columns, either use chan rule or use the `np.ix_` function, which converts two 1D integer arrays to an indexer that selects the square region.

```{python}
import numpy as np

arr = np.arange(32).reshape((8, 4))

arr[[1, 5, 7, 2], [0, 3, 1, 2]]

arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]
```

## Universal Functions: Fast Element-wise Array Functions

+ Unary ufuncs

Function | Description
-------- | -----------
abs, fabs | Compute the absolute value element-wise for integer, floating point, or complex values. Use fabs as a faster alternative for non-complex-valued data
sqrt | Compute the square root of each element. Equivalent to arr ** 0.5
square | Compute the square of each element. Equivalent to arr ** 2
exp | Compute the exponent ex of each element
log, log10, log2, log1p | Natural logarithm (base e), log base 10, log base 2, and log(1 + x), respectively
sign | Compute the sign of each element: 1 (positive), 0 (zero), or -1 (negative)
ceil | Compute the ceiling of each element, i.e. the smallest integer greater than or equal to each element
floor | Compute the floor of each element, i.e. the largest integer less than or equal to each element
rint | Round elements to the nearest integer, preserving the dtype
modf | Return fractional and integral parts of array as separate array
isnan | Return boolean array indicating whether each value is NaN (Not a Number)
isfinite, isinf | Return boolean array indicating whether each element is finite (non-inf, non-NaN) or infinite, respectively
cos, cosh, sin, sinh, tan, tanh | Regular and hyperbolic trigonometric functions
arccos, arccosh, arcsin, arcsinh, arctan, arctanh | Inverse trigonometric functions
logical\_not | Compute truth value of not x element-wise. Equivalent to -arr.

+ Binary ufuncs

Function | Description
-------- | -----------
add | Add corresponding elements in arrays
subtract | Subtract elements in second array from first array
multiply | Multiply array elements
divide, floor_divide | Divide or floor divide (truncating the remainder)
power | Raise elements in first array to powers indicated in second array
maximum, fmax | Element-wise maximum. fmax ignores NaN
minimum, fmin | Element-wise minimum. fmin ignores NaN
mod | Element-wise modulus (remainder of division)
copysign | Copy sign of values in second argument to values in first argument
greater, greater\_equal, less, less\_equal, equal, not\_equal | Perform element-wise comparison, yielding boolean array. Equivalent to infix operators >, >=, <, <=, ==, !=
logical\_and, logical\_or, logical\_xor | Compute element-wise truth value of logical operation. Equivalent to infix operators & |, ^

## Data Processing Using Arrays

+ The `np.meshgrid` function takes two 1D arrays and produces two 2D matrices corresponding to all pairs of (x, y) in the two arrays.

+ The `numpy.where` function is a vectorized version of the ternary expression `x if condition else y`.

```
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]

result = np.where(cond, xarr, yarr)
```

## Mathematical and Statistical Methods

+ Basic array statistical methods

Method | Description
------ | -----------
sum | Sum of all the elements in the array or along an axis. Zero-length arrays have sum 0.
mean | Arithmetic mean. Zero-length arrays have NaN mean.
std, var | Standard deviation and variance, respectively, with optional degrees of freedom adjustment (default denominator n).
min, max | Minimum and maximum.
argmin, argmax | Indices of minimum and maximum elements, respectively.
cumsum | Cumulative sum of elements starting from 0
cumprod | Cumulative product of elements starting from 1

## Sorting

+ NumPy arrays can be sorted _in-place_ using the `sort` method.

+ The top level method `np.sort` returns a _sorted copy_ of an array instead of modifying the array in place.

## Unique and Other Set Logic

+ Array set operations

Method | Description
------ | -----------
unique(x) | Compute the sorted, unique elements in x
intersect1d(x, y) | Compute the sorted, common elements in x and y
union1d(x, y) | Compute the sorted union of elements
in1d(x, y) | Compute a boolean array indicating whether each element of x is contained in y
setdiff1d(x, y) | Set difference, elements in x that are not in y
setxor1d(x, y) | Set symmetric differences; elements that are in either of the arrays, but not both

## File Input and Output with Arrays

+ Storing Arrays on Disk in Binary Format

    - `np.save` and `np.load` are the two workhorse functions for efficiently saving and loading array data on disk. Arrays are saved by default in an uncompressed raw binary format with file extension `.npy`.

    - `np.savez` saves multiple arrays in a zip archive, passing the arrays as keyword arguments: `np.savez('array_archive.npz', a=arr, b=arr)`. When loading an `.npz` file, you get back a dict-like object which loads the individual arrays lazily: `arch = np.load('array_archive.npz'); arch['b']`.
    
+ Saving and Loading Text Files

    - `np.loadtxt` or the more specialized `np.genfromtxt` will at times be useful to load data into vanilla NumPy arrays.
    
    - `np.savetxt` performs the inverse operation: writing an array to a delimited text file. `genfromtxt` is similar to loadtxt but is geared for structured arrays and missing data handling.

## Linear Algebra: `numpy.linalg`

+ `numpy.linalg` has a standard set of matrix decompositions and things like inverse and determinant. These are implemented under the hood using the same industry-standard `Fortran` libraries used in other languages like `MATLAB` and `R`, such as like `BLAS`, `LAPACK`, or possibly (depending on your NumPy build) the `Intel MKL`.

+ Commonly-used `numpy.linalg` functions

Function | Description
-------- | -----------
diag | Return the diagonal (or off-diagonal) elements of a square matrix as a 1D array, or convert a 1D array into a square matrix with zeros on the off-diagonal
dot | Matrix multiplication
trace | Compute the sum of the diagonal elements
det | Compute the matrix determinant
eig | Compute the eigenvalues and eigenvectors of a square matrix
inv | Compute the inverse of a square matrix
pinv | Compute the Moore-Penrose pseudo-inverse inverse of a square matrix
qr | Compute the QR decomposition
svd | Compute the singular value decomposition (SVD)
solve | Solve the linear system Ax = b for x, where A is a square matrix
lstsq | Compute the least-squares solution to y = Xb

## Random Number Generation

+ Partial list of numpy.random functions

Function | Description
-------- | -----------
seed | Seed the random number generator
permutation | Return a random permutation of a sequence, or return a permuted range
shuffle | Randomly permute a sequence in place
rand | Draw samples from a uniform distribution
randint | Draw random integers from a given low-to-high range
randn | Draw samples from a normal distribution with mean 0 and standard deviation 1 (MATLAB-like interface)
binomial | Draw samples a binomial distribution
normal | Draw samples from a normal (Gaussian) distribution
beta | Draw samples from a beta distribution
chisquare | Draw samples from a chi-square distribution
gamma | Draw samples from a gamma distribution
uniform | Draw samples from a uniform [0, 1) distribution

