---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  engine = 'python',
  fig.path = "README-"
)
```

# pandas

## Series and DataFrame

+ `Series` is like a `dict`, and DataFrame is like a nested `dict` of `dicts with common keys`.

```
import pandas as pd
from pandas import Series, DataFrame

sdata1 = {'Ohio': 2, 'Texas': 3, 'Nevada': 5, 'Utah': 8}
series1 = Series(sdata1)

fdata1 = {'Nevada': {           2001: 2.2, 2002: 2.3},
          'Ohio'  : {2000: 1.4, 2001: 1.7, 2002: 3.8}}
       
frame1 = DataFrame(fdata1)
```

+ Possible data inputs to DataFrame constructor

Type | Notes
---- | -----
2D ndarray | A matrix of data, passing optional row and column labels
dict of arrays, lists, or tuples | Each sequence becomes a column in the DataFrame. All sequences must be the same length.
NumPy structured/record array | Treated as the "dict of arrays" case
dict of Series | Each value becomes a column. Indexes from each Series are unioned together to form the result's row index if no explicit index is passed.
dict of dicts | Each inner dict becomes a column. Keys are unioned to form the row index as in the "dict of Series" case.
list of dicts or Series | Each item becomes a row in the DataFrame. Union of dict keys or Series indexes become the DataFrame's column labels
list of lists or tuples | Treated as the "2D ndarray" case
another DataFrame | The DataFrame's indexes are used unless different ones are passed
NumPy MaskedArray | Like the "2D ndarray" case except masked values become NA/missing in the DataFrame result

## Index Objects

+ pandas's Index objects are responsible for holding the axis labels and other metadata (like the axis name or names).

+ Index objects are immutable and thus can't be modified by the user. Immutability is important so that Index objects can be safely shared among data structures.

+ Main Index objects in `pandas`

Class | Description
----- | -----------
Index | The most general Index object, representing axis labels in a NumPy array of Python objects.
Int64Index | Specialized Index for integer values.
MultiIndex | "Hierarchical" index object representing multiple levels of indexing on a single axis. Can be thought of as similar to an array of tuples.
DatetimeIndex | Stores nanosecond timestamps (represented using NumPy’s datetime64 dtype).
PeriodIndex | Specialized Index for Period data (timespans).

+ Index methods and properties

Method | Description
------ | -----------
append | Concatenate with additional Index objects, producing a new Index
diff | Compute set difference as an Index
intersection | Compute set intersection
union | Compute set union
isin | Compute boolean array indicating whether each value is contained in the passed collection
delete | Compute new Index with element at index i deleted
drop | Compute new index by deleting passed values
insert | Compute new Index by inserting element at index i
is_monotonic | Returns True if each element is greater than or equal to the previous element
is_unique | Returns True if the Index has no duplicate values
unique | Compute the array of unique values in the Index

## Essential Functionally

+ Reindexing

    - `reindex` function arguments
    
    Argument | Description
    -------- | -----------
    index | New sequence to use as index. Can be Index instance or any other sequence-like Python data structure. An Index will be used exactly as is without any copying
    method | Interpolation (fill) method, `ffill` or `pad` to fill (or carry) values forward, `bfill` or `backfill` to fill (or carry) values backward.
    fill_value | Substitute value to use when introducing missing data by reindexing
    limit | When forward- or backfilling, maximum size gap to fill
    level | Match simple Index on level of MultiIndex, otherwise select subset of copy Do not copy underlying data if new index is equivalent to old index. True by default (i.e. always copy data).

    - reindexing can be done more succinctly by label-indexing with `ix`.
    
+ Dropping entries from an axis 

`data.drop([index])` is default on dropping row index, dropping column index must specifiy `axis=1`. This is inconsistent with latter indexing, selection and filtering, which is default on indexing and slicing column index, and selecting row index must specifiy `.ix`.

```
data.drop(['row-index'])

data.drop(['col-index'], axis=1)
```
+ Indexing, selection, and filtering

```
data['col-index']

data.ix['row-index'<, 'col-index'>]
```
Indexing options with DataFrame

Type | Notes
---- | -----
obj[val] | Select single column or sequence of columns from the DataFrame. Special case conveniences: boolean array (filter rows), slice (slice rows), or boolean DataFrame (set values based on some criterion).
obj.ix[val] | Selects single row of subset of rows from the DataFrame.
obj.ix[:, val] | Selects single column of subset of columns.
obj.ix[val1, val2] | Select both rows and columns.
reindex method | Conform one or more axes to new indexes.
xs method | Select single row or column as a Series by label.
icol, irow methods | Select single column or row, respectively, as a Series by integer location.
get\_value, set\_value methods | Select single value by row and column label.

## Arithmetic and data alignment

+ Arithmetic such as `+ - * /` between Series and DataFrame will match index, and `NaN` is produced when nomatch.

+ Arithmetic methods suchs as `add sub mul div` with argument `fill_value=0` will fill a special value, like 0, when an axis label is found in one object but not the other.

+ Operations between DataFrame and Series: By default, arithmetic between DataFrame and Series matches the index of the Series on the DataFrame's columns, broadcasting down the rows, e.g., row-by-row operation. If one want to instead matching on the rows, broadcast over the columns, e.g., col-by-col operation, one have to use one of the arithmetic methods with argument `axis=0`. The axis number that you pass is the axis to match on. In this case we mean to match on the DataFrame’s row index and broadcast across.

```
#- Operations between DataFrame and Series
frame = DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), index=['Ohio', 'Texas', 'Nevada', 'Utah'])

## row-by-row operation
series1 = frame.ix[0]
frame - series1

## reindex form union when index not match
series2 = Series(range(3), index=['b', 'e', 'f'])
frame + series2

## col-by-col operation with methods and argument axis
series3 = frame['d']
frame.sub(series3, axis=0)
```

+ Function application and mapping:

    - NumPy ufuncs (element-wise array methods) work fine with pandas objects.
    
    - DataFrame's `apply` method applys a function on 1D arrays to each column (default `axis=0`) or row (`axis=1`).
    
    - DataFrame's `applymap` method and Series `map` method apply a function element-wise on a DataFrame or Series.

+ Sorting and ranking:

    - The `sort_index` method sorts DataFrame or Series lexicographically by row (default `axis=0`) or column (`axis=1`) index, and returns a new, sorted object.
    
    - The `order` method sorts a Series by its values.
    
    - The `sort_index` method with argument `by=[col-index]` sorts a DataFrame w.r.t one or more columns.
    
    - The `rank` methods for Series and DataFrame assigns ranks from one through the number of valid data points in an array. By default rank breaks ties by assigning each group the mean rank. Tie-breaking methods with `rank`: `average` (default) assign the average rank to each entry in the equal group, `min` use the minimum rank for the whole group, `max` use the maximum rank for the whole group, `first` assign ranks in the order the values appear in the data. Ranking is closely related to sorting, it is similar to the indirect sort indices produced by `numpy.argsort`, except that ties are broken according to a rule.
    
## Summarizing and Computing Descriptive Statistics

+ Descriptive and summary statistics

Method | Description
------ | -----------
count | Number of non-NA values
describe | Compute set of summary statistics for Series or each DataFrame column
min, max | Compute minimum and maximum values
argmin, argmax | Compute index locations (integers) at which minimum or maximum value obtained, respectively
idxmin, idxmax | Compute index values at which minimum or maximum value obtained, respectively
quantile | Compute sample quantile ranging from 0 to 1
sum | Sum of values
mean | Mean of values
median | Arithmetic median (50% quantile) of values
mad | Mean absolute deviation from mean value
var | Sample variance of values
std | Sample standard deviation of values
skew | Sample skewness (3rd moment) of values
kurt | Sample kurtosis (4th moment) of values
cumsum | Cumulative sum of values
cummin, cummax | Cumulative minimum or maximum of values, respectively
cumprod | Cumulative product of values
diff | Compute 1st arithmetic difference (useful for time series)
pct_change | Compute percent changes

+ Options for reduction methods, like `sum`

Method | Description
------ | -----------
axis | Axis to reduce over. 0 for DataFrame’s rows and 1 for columns.
skipna | Exclude missing values, True by default.
level | Reduce grouped by level if the axis is hierarchically-indexed (MultiIndex).

## Correlation and Covariance

+ The `corr` method of Series computes the correlation of the overlapping, non-NA, aligned-by-index values in two Series. Relatedly, `cov` computes the covariance.

+ DataFrame's `corrwith` method computes pairwise correlations between a DataFrame's columns or rows with another Series or DataFrame. 

    - Passing a Series returns a Series with the correlation value computed for each column. 
    
    - Passing a DataFrame computes the correlations of matching column names. 
    
    - Passing axis=1 does things row-wise instead. 
    
    - In all cases, the data points are aligned by label before computing the correlation.
    
## Unique Values, Value Counts, and Membership

+ Unique, value counts, and binning methods

Method | Description
------ | -----------
isin | Compute boolean array indicating whether each Series value is contained in the passed sequence of values.
unique | Compute array of unique values in a Series, returned in the order observed.
value_counts | Return a Series containing unique values as its index and frequencies as its values, ordered count in descending order.

+ `value_counts` like `R table()`, and also available as a top-level pandas method that can be used with any array or sequence.

+ Ex: use `pandas.value_counts()` to compute a histogram on multiple related columns in a DataFrame:

```
data = DataFrame({'Qu1': [1, 3, 4, 3, 4], 'Qu2': [2, 3, 1, 2, 3], 'Qu3': [1, 5, 2, 4, 4]})
rslt = data.apply(pd.value_counts).fillna(0)
```

## Handling Missing Data

+ `pandas` uses the floating point value `NaN` (Not a Number) to represent missing data in both floating as well as in non-floating point arrays like string data. It is just used as a _sentinel_ that can be easily detecte. Both `np.nan` and built-in `None` are treated as `NA` or `NaN` in `pandas`.

+ NA handling methods

Argument | Description
-------- | -----------
dropna | Filter axis labels based on whether values for each label have missing data, with varying thresholds for how much missing data to tolerate.
fillna | Fill in missing data with some value or using an interpolation method such as 'ffill' or 'bfill'.
isnull | Return like-type object containing boolean values indicating which values are missing / NA.
notnull | Negation of isnull.

+ `dropna`:

    - Use `dropna` on a Series returns the Series with only the non-null data and index values. 
    
    - Use `dropna` on a DataFrame returns rows containing no missing value (default is to drop any row containing a missing value), passing `how='all'` will returns rows containing not all missing value (drop rows that are all NA). Dropping columns in the same way is only a matter of passing `axis=1`.

+ `fillna`:

    - Calling `fillna` with a constant replaces missing values with that value.
    
    - Calling `fillna` with a dict you can use a different fill value for each column.
    
    - Passing `inplace=True` can modify the existing object in place, default is returning a new object.
    
    - `fillna` function arguments
    
    Argument | Description
    -------- | -----------
    value | Scalar value or dict-like object to use to fill missing values
    method | Interpolation, by default 'ffill' if function called with no other arguments
    axis | Axis to fill on, default axis=0
    inplace | Modify the calling object without producing a copy
    limit | For forward and backward filling, maximum number of consecutive periods to fill
    
## Hierarchical Indexing

+ Hierarchical indexing in `pandas` enables multiple (two or more) index levels on an axis. Somewhat abstractly, it provides a way to work with higher dimensional data in a lower dimensional form. In the most simply case, two index levels, think the outer level index as row index, whereas inner level index as column index.

    - The `stack` and `unstack` convert back and forth between MultiIndex and row-column-index.

+ Reordering and sorting levels:

    - The `swaplevel` takes two level numbers or names and returns a new object with the levels interchanged (but the data is otherwise unaltered).
    
    - The `sortlevel` sorts the data (stably) using only the index values (not data values) in a single level.
    
    - Data selection performance is much better on hierarchically indexed objects if the index is lexicographically sorted starting with the outermost level, that is, the result of calling `sortlevel(0)`  or `sort_index()`.
    
## Using a DataFrame’s Columns as Index and Vice Versa

+ DataFrame's `set_index` function will create a new DataFrame using one or more of its columns as the index `frame2 = frame.set_index(['col1', 'col2'])`.

+ The columns used in `set_index` are removed from the DataFrame by default, though you can leave them in by passing `drop=False`.

+ `reset_index`, on the other hand, does the opposite of `set_index`, the hierarchical index levels are are moved into the columns.

## Integer Indexing

+ `pandas` would fallback  on integer indexing when user specified. However, it is ambiguous when Series or DataFrame also have a integer labelled index.

+ To keep things consistent, if you have an axis index containing indexers, data selection with integers will always be label-oriented. This includes slicing with ix, too.

+ In cases where reliable position-based indexing is needed regardless of the index type, use the `iget_value` method from Series and `irow` and `icol` methods from DataFrame.

## Panel Data

+ `pandas` design panel data as a three-dimensional analogue of DataFrame.

+ To create a Panel, use a dict of DataFrame objects or a three-dimensional ndarray - `item x major x minor`. Each item (the analogue of columns in a DataFrame) in the Panel is a DataFrame, and `ix`-based label indexing generalizes to three dimensions.

+ An alternate way to represent panel data, especially for fitting statistical models, is in "stacked" DataFrame form `paneldata.to_frame()` - stacked DataFrame data with `item as column index, major x minor as row index`, and the inverse is `stackedframedata.to_panel()`.


